# Generated by Django 2.2.10 on 2020-03-16 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=7, null=True)),
                ('user_style', models.CharField(blank=True, choices=[('semiformal', 'Semi-formal'), ('formal', 'Formal'), ('casual', 'Casual')], max_length=12, null=True)),
                ('user_class', models.CharField(blank=True, choices=[('Upper', 'More than $50'), ('U_mid', '$40 - $50'), ('L_mid', '$20 - $40'), ('Lower', 'Less than $20')], max_length=20, null=True)),
                ('user_brands', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
