# Generated by Django 2.2.10 on 2020-03-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200321_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_brands',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
