# Generated by Django 2.2.11 on 2020-03-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200321_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_style',
            field=models.CharField(blank=True, choices=[('Formal', 'Formal'), ('Semi-Formal', 'Semi-Formal'), ('Casual', 'Casual')], max_length=12, null=True),
        ),
    ]
