# Generated by Django 2.2.11 on 2020-03-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200326_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_class',
            field=models.CharField(blank=True, choices=[('Upper', 'More than $50'), ('MUpper', '$40 - $50'), ('MLower', '$20 - $40'), ('Lower', 'Less than $20')], max_length=20, null=True),
        ),
    ]
