# Generated by Django 2.2.10 on 2020-03-13 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommend', '0003_auto_20200307_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user_rating',
            field=models.ManyToManyField(blank=True, related_name='rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='users_interseted',
            field=models.ManyToManyField(blank=True, related_name='interested', to=settings.AUTH_USER_MODEL),
        ),
    ]
