# Generated by Django 2.2.10 on 2020-03-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0004_auto_20200313_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.URLField(max_length=500, null=True, unique=True),
        ),
    ]
