# Generated by Django 2.2.10 on 2020-03-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0005_auto_20200313_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user_rating',
        ),
        migrations.AddField(
            model_name='item',
            name='ratings',
            field=models.IntegerField(blank=True, choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Neutral'), (4, 'Good'), (5, 'Very Good')], null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(choices=[('Zara', 'Zara'), ('Gap', 'Gap'), ("Levi Strauss & Co. (Levi's)", "Levi Strauss & Co. (Levi's)"), ('Mango', 'Mango'), ('Monsoon', 'Monsoon'), ('Pull & Bear', 'Pull & Bear'), ('Bershka', 'Bershka'), ('American Eagle (AE)', 'American Eagle (AE)'), ('Forever 21', 'Forever 21'), ('Stradivarious', 'Stradivarious'), ('Parfois', 'Parfois'), ('British Home Stores (BHS)', 'British Home Stores (BHS)'), ('United States Polo Assn.', 'United States Polo Assn.'), ('Adidas', 'Adidas'), ('Tommy Hilfiger', 'Tommy Hilfiger'), ('BOGGI', 'BOGGI'), ('HACKETT', 'HACKETT'), ('Massimo Dutti', 'Massimo Dutti'), ('Punt Roma', 'Punt Roma'), ('H&M', 'H&M'), ('Next', 'Next'), ('Nike', 'Nike')], max_length=120),
        ),
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=7),
        ),
    ]
