# Generated by Django 2.2.10 on 2020-03-19 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommend', '0007_auto_20200319_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='neck',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='ocassion',
            field=models.CharField(choices=[('formal', 'Formal'), ('semiformal', 'Semi-Formal'), ('casual', 'Casual')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sleeve',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='style',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='user_ratings',
            field=models.ManyToManyField(blank=True, through='recommend.ItemRating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='waist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='website_url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(choices=[('Zara', 'Zara'), ('Gap', 'Gap'), ("Levi Strauss & Co. (Levi's)", "Levi Strauss & Co. (Levi's)"), ('Mango', 'Mango'), ('Monsoon', 'Monsoon'), ('Pull & Bear', 'Pull & Bear'), ('Bershka', 'Bershka'), ('American Eagle (AE)', 'American Eagle (AE)'), ('Forever 21', 'Forever 21'), ('Stradivarious', 'Stradivarious'), ('Parfois', 'Parfois'), ('British Home Stores (BHS)', 'British Home Stores (BHS)'), ('United States Polo Assn.', 'United States Polo Assn.'), ('Adidas', 'Adidas'), ('Tommy Hilfiger', 'Tommy Hilfiger'), ('BOGGI', 'BOGGI'), ('HACKETT', 'HACKETT'), ('Massimo Dutti', 'Massimo Dutti'), ('Punt Roma', 'Punt Roma'), ('H&M', 'H&M'), ('Next', 'Next'), ('Nike', 'Nike')], max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('fullbody', 'Full Body'), ('shoes', 'Shoes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='itemrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
