# Generated by Django 2.2.10 on 2020-03-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0008_auto_20200320_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
