# Generated by Django 2.2.10 on 2020-03-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0010_auto_20200320_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='_type',
            new_name='item_type',
        ),
    ]
