# Generated by Django 2.2.10 on 2020-03-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0011_auto_20200320_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('Full Body', 'Full Body'), ('Shoes', 'Shoes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7),
        ),
        migrations.AlterField(
            model_name='item',
            name='ocassion',
            field=models.CharField(choices=[('Formal', 'Formal'), ('Semi-Formal', 'Semi-Formal'), ('Casual', 'Casual')], max_length=50, null=True),
        ),
    ]
